hidden:
- input: '7 3

    -1 4 -5 3 -4 -3 3'
  output: ''
- input: '5 3

    4 -2 0 -4 -1'
  output: ''
- input: '8 3

    5 -1 5 -1 4 -3 -3 1'
  output: ''
- input: '1 2

    -5'
  output: ''
- input: '2 4

    -3 4'
  output: ''
- input: '4 4

    -5 3 2 -3'
  output: ''
- input: '8 5

    0 -1 -1 3 -2 1 -5 -1'
  output: ''
- input: '2 5

    5 5'
  output: ''
- input: '5 1

    -3 -3 5 -1 -5'
  output: ''
- input: '1 1

    -3'
  output: ''
- input: '6 1

    4 1 3 0 -3 -3'
  output: ''
- input: '2 3

    -5 -3'
  output: ''
- input: '8 4

    0 2 -4 4 -4 2 -2 1'
  output: ''
- input: '4 2

    2 1 -5 -2'
  output: ''
- input: '1 3

    4'
  output: ''
- input: '3 5

    -2 -2 0'
  output: ''
- input: '5 3

    -5 4 4 -3 0'
  output: ''
- input: '6 1

    1 -3 -2 4 3 -5'
  output: ''
- input: '8 2

    0 3 -3 -3 -5 4 -2 -2'
  output: ''
- input: '2 3

    1 0'
  output: ''
- input: '8 4

    2 -5 5 -2 -4 2 1 5'
  output: ''
- input: '8 3

    2 3 -4 3 -2 -2 1 -3'
  output: ''
- input: '8 2

    -2 0 2 -2 -1 -4 -5 4'
  output: ''
- input: '8 4

    2 1 3 4 -1 -1 5 3'
  output: ''
- input: '5 1

    -4 1 2 3 -2'
  output: ''
- input: '2 2

    0 -1'
  output: ''
- input: '2 3

    -1 4'
  output: ''
- input: '2 1

    4 1'
  output: ''
- input: '3 5

    2 -3 -1'
  output: ''
- input: '4 4

    5 -3 -3 0'
  output: ''
- input: '4 4

    4 -4 1 -1'
  output: ''
- input: '5 5

    -4 4 1 -4 2'
  output: ''
- input: '5 3

    0 -2 -5 5 0'
  output: ''
- input: '5 5

    -5 4 0 1 2'
  output: ''
- input: '3 1

    0 5 0'
  output: ''
public:
- input: '5 3

    1 2 3 4 5

    SET 2 10

    COUNT 0 4 3 10

    COUNT 2 2 10 10

    '
  output: '3

    1'
- input: '1 1

    1'
  output: ''
- input: '1 1

    1'
  output: ''
samples:
- input: '3 1

    1 5 2

    COUNT 0 2 2 5

    '
  output: '2'
- input: '1 1

    1'
  output: ''
